"""
usage table: supa_usage_table

schema:

create table public.supa_usage_table (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id text null,
  chat_id text null,
  query_id text null,  -- IMPORTANT: Must have UNIQUE constraint for UPSERT to work
  conversation_title text null,
  query_type text null,
  query_subtype text null,
  app_version double precision null,
  status text null,
  total_time double precision null,
  updated_at timestamp without time zone null,
  started_at timestamp without time zone null,
  completed_at timestamp without time zone null,
  duration_seconds integer null,
  num_steps smallint null,
  step_stats json null,
  constraint supa_usage_table_pkey primary key (id),
  constraint supa_usage_table_query_id_key unique (query_id)  -- Required for UPSERT by query_id
) TABLESPACE pg_default;

Usage Flow:
1. Frontend creates stub row with status='pending' and unique query_id
2. Agent UPSERTs by query_id → status='started' then 'running' (updates existing stub)
3. Agent completes → updates by query_id → status='completed' or 'failed'

All updates use query_id as the identifier (not the auto-generated id).
"""

import os
import json
import time
import threading
from datetime import datetime, timezone
from typing import Optional, Dict, Any, List
from collections import Counter
import logging
from enum import Enum
from faraday.openai_clients import llm_client
from faraday.logging.updates import MessageType
from pydantic import BaseModel, Field
import asyncio
from threading import Timer
from faraday.storage import get_storage_backend


# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Per-run billing estimates (USD) from logged token totals and tool-call counts.
COST_PER_TOKEN = 1e-5
COST_PER_TOOL_CALL = 0.01


class CreditSystemError(RuntimeError):
    """Raised when balance or billing state cannot be read or updated."""


class InsufficientBalanceError(CreditSystemError):
    def __init__(self, user_id: str, min_required: float, actual: float) -> None:
        self.user_id = user_id
        self.min_required = min_required
        self.actual = actual
        super().__init__(
            f"Insufficient balance for user {user_id}: need > ${min_required:.4f}, have ${actual:.4f}"
        )


def generate_conversation_title_gpt41mini(task_query: str) -> str:
    """Generate a title for a conversation based on its content."""

    system_prompt = """
    You are naming a new chat based on the user's first message.
    Produce a concise, high-signal title that captures the intent or likely outcome.

    Output requirements:
    - Output only the title text; no extra words, quotes, labels, or markdown.
    - Use Title Case (Capitalize Major Words); no trailing punctuation.
    - Paraphrase the query; do not copy it verbatim.
    - Keep the title length between 35-50 characters.
    - Exclude sensitive info, IDs, file names, or molecule identifiers.

    Do not attempt to solve the task.
    """
    response = llm_client.responses.create(
        instructions=system_prompt,
        model="gpt-4.1-mini",
        input=[{"role": "user", "content": task_query}]
    )
    return response.output_text


class UsageTracker:
    """
    Helper class to track CodeActAgent usage metrics with integrated balance management.
    
    This class handles:
    - Task tracking and logging
    - Balance checking and deduction
    - Transaction logging
    - Step statistics
    
    Balance System Features:
    - Pre-task balance verification (> $0)
    - Usage-based dollar deduction on completion
    - Transaction audit logging
    - Support for dev/prod environments
    
    Usage Example:
    
        # Basic usage with balance checking
        tracker = UsageTracker(
            user_id="user123",
            chat_id="chat456",
            query_id="query789",
            mode="prod"
        )
        
        # Create usage record (automatically checks balance)
        record_id = tracker.create_usage_record("Optimize ADMET properties")
        
        if not record_id:
            # Insufficient balance or error
            balance = tracker.get_dollar_balance()
            print(f"Cannot start task. Current balance: {balance}")
            return
        
        # Log task progress
        tracker.log_step(MessageType.THOUGHT, "Analyzing molecule...")
        tracker.log_tool_call("rdkit_compute", {"mol": "CCO"}, execution_time=1.2)
        
        # Complete task (deducts actual dollar cost)
        tracker.complete_usage_record(final_status="completed")
        
        # Or handle errors without charging for the run
        tracker.complete_usage_record(
            final_status="error",
            error_message="RDKit parsing failed",
        )
    
    Advanced Usage:
    
        # Check balance before starting
        has_balance, balance = tracker.check_balance_available(min_balance_dollars=0.0)
        if not has_balance:
            raise InsufficientBalanceError(tracker.user_id, 0.0, balance or 0.0)
        
        # Get current balance
        balance = tracker.get_dollar_balance()
        print(f"Remaining balance: {balance}")
    """
    
    def __init__(self, user_id: str,
     chat_id: str,
     query_id: str = None,
     enable_batching: bool = True,
     batch_interval: float = 5.0,
     app_version: float = 0.64,
     mode: str = "dev",
     project_label: str = "default",
     model: str = None
     ):
        self.user_id = user_id
        self.chat_id = chat_id
        self.query_id = query_id
        self.project_label = project_label  # Project label for tracking
        self.model = model  # Model name for tracking
        self.storage = get_storage_backend()
        self.current_record_id: Optional[int] = None
        self.start_time: Optional[float] = None
        self.step_count = 0
        self.step_stats: List[Dict[str, Any]] = []
        self.step_order: List[str] = []  # Track order of steps
        self.step_type_counts: Counter = Counter()  # Track count of each step type
        self.conversation_title: Optional[str] = None  # Track conversation title
        self.record_completed: bool = False  # Track if record has been marked as completed

        self.app_version = app_version
        # Add batching for database operations
        self.enable_batching = enable_batching
        self.batch_interval = batch_interval
        self.pending_updates = []
        self.batch_timer: Optional[Timer] = None
        self.last_db_update = time.time()

        if mode not in ["dev", "prod"]:
            raise ValueError(f"Invalid mode: {mode}. Must be 'dev' or 'prod'")
        self.mode = mode
    
    def get_credit_balance(self) -> Optional[float]:
        """
        Get the current dollar balance for the user.
        
        Returns:
            Current dollar balance if found, None if error or not found
        """
        return self.get_dollar_balance()
    
    def get_dollar_balance(self) -> Optional[float]:
        """
        Get the current dollar balance for the user.
        
        Returns:
            Current dollar balance if found, None if error or not found
        """
        try:
            balance = self.storage.get_user_balance(self.user_id, mode=self.mode)
            if balance is not None:
                logger.info(f"User {self.user_id} has ${balance:.4f} balance")
                return float(balance)
            else:
                logger.warning(f"No balance record found for user {self.user_id}")
                return None
                
        except Exception as e:
            logger.error(f"Error getting dollar balance: {str(e)}")
            return None
    
    def deduct_dollar_balance(self, amount: float, reason: str = "task_completion") -> bool:
        """
        Deduct dollars from user's balance with transaction logging.
        
        Args:
            amount: Dollar amount to deduct
            reason: Reason for deduction (for logging)
            
        Returns:
            True if successful, False otherwise
        """
        if amount <= 0:
            logger.warning(f"Skipping deduction of non-positive amount: ${amount:.4f}")
            return True
        
        try:
            # Get current balance
            current_balance = self.get_dollar_balance()
            
            if current_balance is None:
                logger.error("Cannot deduct dollars: failed to get current balance")
                return False
            
            if current_balance < amount:
                logger.warning(f"User {self.user_id} has insufficient balance: ${current_balance:.4f} < ${amount:.4f}, deducting remaining balance")
                # Deduct what's available (go to zero rather than failing)
                amount = current_balance
            
            # Calculate new balance
            new_balance = max(current_balance - amount, 0.0)
            
            updated = self.storage.set_user_balance(self.user_id, new_balance, mode=self.mode)
            if updated:
                logger.info(f"Deducted ${amount:.4f} from user {self.user_id}: ${current_balance:.4f} -> ${new_balance:.4f} (reason: {reason})")
                return True
            else:
                logger.error("Dollar balance deduction failed: no data returned")
                return False
                
        except Exception as e:
            logger.error(f"Error deducting dollar balance: {str(e)}")
            return False
    
    def check_balance_available(self, min_balance_dollars: float = 0.0, raise_on_insufficient: bool = False) -> tuple[bool, Optional[float]]:
        """
        Check if user has sufficient dollar balance to proceed.
        
        Args:
            min_balance_dollars: Minimum dollar balance required (default 0.0)
            raise_on_insufficient: If True, raise InsufficientCreditsError instead of returning False
            
        Returns:
            Tuple of (has_sufficient_balance, current_balance)
            
        Raises:
            InsufficientBalanceError: If raise_on_insufficient=True and user has insufficient balance
            CreditSystemError: If there's an error retrieving balance
        """
        try:
            current_balance = self.get_dollar_balance()
            
            if current_balance is None:
                error_msg = f"Could not retrieve balance for user {self.user_id}"
                logger.error(error_msg)
                if raise_on_insufficient:
                    raise CreditSystemError(error_msg)
                return (False, None)
            
            has_balance = current_balance > min_balance_dollars
            
            if not has_balance:
                logger.warning(f"Insufficient balance for user {self.user_id}: has ${current_balance:.4f}, needs > ${min_balance_dollars:.4f}")
                if raise_on_insufficient:
                    raise InsufficientBalanceError(self.user_id, min_balance_dollars, current_balance)
            
            return (has_balance, current_balance)
            
        except (InsufficientBalanceError, CreditSystemError):
            raise  # Re-raise our custom exceptions
        except Exception as e:
            logger.error(f"Error checking balance: {str(e)}")
            if raise_on_insufficient:
                raise CreditSystemError(f"Error checking balance: {str(e)}")
            return (False, None)
    
    def _schedule_batch_update(self):
        """Schedule a batched database update to prevent SSE clogging"""
        if not self.enable_batching:
            return
            
        # Cancel existing timer
        if self.batch_timer:
            self.batch_timer.cancel()
        
        # Schedule new batch update
        self.batch_timer = Timer(self.batch_interval, self._execute_batch_update)
        self.batch_timer.start()
    
    def _execute_batch_update(self):
        """Execute batched database update"""
        try:
            if self.current_record_id and (time.time() - self.last_db_update) >= self.batch_interval:
                self._update_record_now()
                self.last_db_update = time.time()
        except Exception as e:
            logger.error(f"Error in batch update: {str(e)}")
    
    def _update_record_now(self):
        """Immediately update the database record by query_id"""
        if not self.query_id:
            logger.warning("No query_id available for record update")
            return False
        
        # Skip update if record has been marked as completed
        if self.record_completed:
            logger.info(f"Skipping batch update for completed record (query_id={self.query_id})")
            return True
            
        try:
            current_time = datetime.now(timezone.utc).isoformat()
            
            # Create comprehensive step stats including order and counts
            comprehensive_stats = {
                "steps": self.step_stats,
                "summary": self.get_step_summary()
            }
            
            update_data = {
                "updated_at": current_time,
                "num_steps": self.step_count,
                "step_stats": comprehensive_stats,
            }
            
            # Add duration if we have start time
            if self.start_time:
                duration = time.time() - self.start_time
                update_data["duration_seconds"] = int(duration)
                update_data["total_time"] = duration
            
            updated = self.storage.update_usage_record_by_query_id(
                query_id=self.query_id,
                status="running",
                additional_data=update_data,
                mode=self.mode,
            )
            
            if updated:
                logger.info(f"Batch updated usage record by query_id={self.query_id}")
                return True
            logger.warning(f"No usage record updated for query_id={self.query_id}")
            return False
                
        except Exception as e:
            logger.error(f"Error in immediate record update (query_id={self.query_id}): {str(e)}")
            return False
    
    def _check_and_generate_conversation_title(self, query_string: str) -> Optional[str]:
        """
        Check if a conversation title exists for this user_id + chat_id combination.
        If not, generate one using the first query.
        
        Args:
            query_string: The task query string to generate title from
            
        Returns:
            The conversation title (existing or newly generated)
        """
        try:
            existing_title = self.storage.get_conversation_title(
                user_id=self.user_id,
                chat_id=self.chat_id,
                mode=self.mode,
            )
            if existing_title:
                logger.info(f"Found existing conversation title: {existing_title}")
                return existing_title
            else:
                # Generate new conversation title
                logger.info("No conversation title found, generating new one...")
                new_title = generate_conversation_title_gpt41mini(query_string)
                logger.info(f"Generated conversation title: {new_title}")
                return new_title
                
        except Exception as e:
            logger.error(f"Error checking/generating conversation title: {str(e)}")
            # Return a truncated version of the query as fallback (max 24 chars)
            truncated = query_string[:24].strip()
            if len(query_string) > 24:
                truncated += "..."
            logger.info(f"Using truncated query as title: {truncated}")
            return truncated
    
    def create_usage_record(
        self,
        query_string: str,
        check_credits: bool = True,
        first_query_bool: Optional[bool] = None,
        query_text: Optional[str] = None,
    ) -> Optional[int]:
        """
        Create or update a usage record when a task starts.
        Uses UPSERT by query_id - updates existing pending stub from frontend, or inserts new record.
        Checks credit availability before proceeding.
        
        Args:
            query_string: The task query string
            check_credits: Whether to check credits before creating record (default True)
            
        Returns:
            Record ID if successful, None otherwise (including insufficient credits)
        """
        
        # Check balance BEFORE starting the task
        if check_credits:
            has_balance, balance = self.check_balance_available(min_balance_dollars=0.0)
            
            if not has_balance:
                logger.error(f"Cannot start task: user {self.user_id} has insufficient balance (balance: {balance})")
                return None
            
            logger.info(f"Balance check passed: user {self.user_id} has ${balance:.4f} balance")
        
        short_system_prompt = """
        Respond with high-level key terms that describe the task, up to 3 key terms. Separate them using commas.
        These should be task-oriented.
        Do not add molecule identifiers or sensitive information.
        Response with only the key terms, do not add any other text.

        A few good examples:
        - ADMET Optimization
        - Solutbility Prediction
        - Drug Design, Binding Affinity Optimization,Scaffold Modification
        """

        long_system_prompt = """
        Create a concise description of the query (up to 6 words).
        IMPORTANT: DO NOT ATTEMPT TO SOLVE THE TASK.
        Do not add molecule identifiers or sensitive information.
        Response with only the description, do not add any other text.
        """

        # Check and generate conversation title if needed
        self.conversation_title = self._check_and_generate_conversation_title(query_string)

        # Generate query type classifications
        short_response = llm_client.responses.create(
            model="gpt-4.1-mini",
            input=[
                {"role": "system", "content": short_system_prompt},
                {"role": "user", "content": f"Query: {query_string}"}
            ],
        )  

        long_response = llm_client.responses.create(
            model="gpt-4.1-mini",
            input=[
                {"role": "system", "content": long_system_prompt},
                {"role": "user", "content": f"Query: {query_string}"}
            ],
        )   

        short_query_type = short_response.output_text
        long_query_type = long_response.output_text

        try:
            self.start_time = time.time()
            current_time = datetime.now(timezone.utc).isoformat()
            
            # Data for upsert - updates existing pending stub or creates new record
            data = {
                "user_id": self.user_id,
                "chat_id": self.chat_id,
                "query_id": self.query_id,
                "conversation_title": self.conversation_title,
                "query_type": short_query_type,
                "query_subtype": long_query_type,
                "app_version": self.app_version,
                "project_label": self.project_label,
                "status": "started",
                "started_at": current_time,
                "updated_at": current_time,
                "num_steps": 0,
                "step_stats": [],
                "mode": self.mode,
            }

            # Persist query text for every query
            data["query_text"] = query_text if query_text is not None else query_string
            if first_query_bool is not None:
                data["first_query_bool"] = bool(first_query_bool)
            
            # Add model if available
            if self.model:
                data["model"] = self.model
            
            created = self.storage.create_usage_record(data)
            
            if created:
                self.current_record_id = created.get("id")
                logger.info(f"Upserted usage record by query_id={self.query_id}, got record id={self.current_record_id} for user {self.user_id}")
                logger.info(f"Conversation title: {self.conversation_title}")
                return self.current_record_id
            else:
                logger.error("Failed to upsert usage record - no data returned")
                return None
                
        except Exception as e:
            logger.exception(
                "Error upserting usage record (query_id=%s, user_id=%s, chat_id=%s)",
                self.query_id,
                self.user_id,
                self.chat_id,
            )
            return None
    
    def update_usage_record(self, status: str = "running", additional_data: Optional[Dict[str, Any]] = None) -> bool:
        """
        Update an existing usage record with current progress by query_id
        
        Args:
            status: Current status of the task
            additional_data: Additional data to update
            
        Returns:
            True if successful, False otherwise
        """
        if not self.query_id:
            logger.warning("No query_id available to update usage record")
            return False

        # Never downgrade a terminal/completed record back into an in-progress state.
        # This can happen if late/background processes (e.g., first DB flush)
        # attempt to mark the task as "running" after completion.
        if self.record_completed:
            logger.info(
                f"Skipping usage record update for completed record (query_id={self.query_id}, requested_status={status})"
            )
            return True
            
        try:
            current_time = datetime.now(timezone.utc).isoformat()
            
            # Create comprehensive step stats including order and counts
            comprehensive_stats = {
                "steps": self.step_stats,
                "summary": self.get_step_summary()
            }
            
            update_data = {
                "updated_at": current_time,
                "num_steps": self.step_count,
                "step_stats": comprehensive_stats,
            }
            
            # Add model if available
            if self.model:
                update_data["model"] = self.model
            
            # Add duration if we have start time
            if self.start_time:
                duration = time.time() - self.start_time
                update_data["duration_seconds"] = int(duration)
                update_data["total_time"] = duration
            
            # Add any additional data
            if additional_data:
                update_data.update(additional_data)
            
            updated = self.storage.update_usage_record_by_query_id(
                query_id=self.query_id,
                status=status,
                additional_data=update_data,
                mode=self.mode,
            )
            if updated:
                logger.info(f"Updated usage record by query_id={self.query_id} with status: {status}")
                return True
            logger.warning(f"No usage record updated for query_id={self.query_id}")
            return False
                
        except Exception as e:
            logger.error(f"Error updating usage record (query_id={self.query_id}): {str(e)}")
            return False
    
    def complete_usage_record(self, final_status: str = "completed", error_message: Optional[str] = None) -> bool:
        """
        Mark a usage record as completed and apply dollar billing for successful runs.
        Updates by query_id (unique identifier from frontend).
        
        Args:
            final_status: Final status of the task
            error_message: Error message if task failed
            
        Returns:
            True if successful, False otherwise
        """
        if not self.query_id:
            logger.warning("No query_id available to complete usage record")
            return False
            
        try:
            current_time = datetime.now(timezone.utc).isoformat()
            
            # Create comprehensive step stats including order and counts
            comprehensive_stats = {
                "steps": self.step_stats,
                "summary": self.get_step_summary()
            }
            
            update_data = {
                "completed_at": current_time,
                "updated_at": current_time,
                "num_steps": self.step_count,
                "step_stats": comprehensive_stats,
            }
            
            # Add model if available
            if self.model:
                update_data["model"] = self.model
            
            # Add final duration
            if self.start_time:
                duration = time.time() - self.start_time
                update_data["duration_seconds"] = int(duration)
                update_data["total_time"] = duration
            
            # Add error message to step_stats if provided
            if error_message:
                error_step = {
                    "step_type": "error",
                    "timestamp": current_time,
                    "error_message": error_message
                }
                self.step_stats.append(error_step)
                self.step_order.append("error")
                self.step_type_counts["error"] += 1
                
                # Update comprehensive stats with error
                comprehensive_stats["steps"] = self.step_stats
                comprehensive_stats["summary"] = self.get_step_summary()
                update_data["step_stats"] = comprehensive_stats
            
            # Calculate cost for this run (for both usage table and credits table)
            cost_for_this_run = 0.0
            if final_status == "completed":
                total_tokens = self.get_total_tokens()
                token_cost = total_tokens * COST_PER_TOKEN
                total_tool_calls = self.get_total_tool_calls()
                tool_call_cost = total_tool_calls * COST_PER_TOOL_CALL
                cost_for_this_run = token_cost + tool_call_cost
                
                # Add cost to usage table update (per-run cost)
                update_data["usage_cost_cumulative_dollars"] = cost_for_this_run
            
            updated = self.storage.complete_usage_record_by_query_id(
                query_id=self.query_id,
                final_status=final_status,
                final_data=update_data,
                mode=self.mode,
            )
            if not updated:
                logger.warning(f"No usage record completed for query_id={self.query_id}")
                return False
            
            # Mark record as completed to prevent batch updates from overwriting
            self.record_completed = True

            # Update usage_cost_cumulative_dollars in credits table for successful completions
            if final_status == "completed" and cost_for_this_run > 0:
                try:
                    current_cumulative = self.storage.get_usage_cost_cumulative(
                        user_id=self.user_id,
                        mode=self.mode,
                    )
                    
                    new_cumulative = current_cumulative + cost_for_this_run
                    
                    self.storage.set_usage_cost_cumulative(
                        user_id=self.user_id,
                        value=new_cumulative,
                        mode=self.mode,
                    )
                    
                    # Get values for logging
                    total_tokens = self.get_total_tokens()
                    token_cost = total_tokens * COST_PER_TOKEN
                    total_tool_calls = self.get_total_tool_calls()
                    tool_call_cost = total_tool_calls * COST_PER_TOOL_CALL
                    
                    logger.info(f"Updated usage_cost_cumulative_dollars: ${current_cumulative:.4f} + ${cost_for_this_run:.4f} = ${new_cumulative:.4f} "
                               f"(tokens: {total_tokens} @ ${COST_PER_TOKEN}/token = ${token_cost:.4f}, "
                               f"tool_calls: {total_tool_calls} @ ${COST_PER_TOOL_CALL}/call = ${tool_call_cost:.2f})")
                    logger.info(f"Usage table record (query_id={self.query_id}) updated with run cost: ${cost_for_this_run:.4f}")
                except Exception as cost_error:
                    logger.error(f"Failed to update usage_cost_cumulative_dollars: {cost_error}")
                
                # Deduct run cost from user_balance_dollars
                try:
                    deduct_success = self.deduct_dollar_balance(
                        amount=cost_for_this_run,
                        reason=f"run_cost_task_{self.query_id}"
                    )
                    if deduct_success:
                        logger.info(f"Successfully deducted ${cost_for_this_run:.4f} from user_balance_dollars for task (query_id={self.query_id})")
                    else:
                        logger.error(f"Failed to deduct ${cost_for_this_run:.4f} from user_balance_dollars for task (query_id={self.query_id})")
                except Exception as deduct_error:
                    logger.error(f"Failed to deduct from user_balance_dollars: {deduct_error}")

            # If we get here without exception, the update succeeded
            logger.info(f"Completed usage record (query_id={self.query_id}) with status: {final_status}")

            return True
                
        except Exception as e:
            logger.error(f"Error completing usage record (query_id={self.query_id}): {str(e)}")
            return False
    
    def log_step(self, step_type: MessageType, content: str, metadata: Optional[Dict[str, Any]] = None) -> None:
        """
        Log a step in the agent's execution
        
        Args:
            step_type: Type of step from MessageType enum
            content: Content of the step
            metadata: Additional metadata for the step
        """
        self.step_count += 1
        
        # Track step order and counts
        step_type_str = step_type.value if isinstance(step_type, MessageType) else step_type
        self.step_order.append(step_type_str)
        self.step_type_counts[step_type_str] += 1
        
        step_data = {
            "step_number": self.step_count,
            "step_type": step_type_str,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "content_length": len(content) if content else 0
        }
        
        if metadata:
            step_data.update(metadata)
        
        self.step_stats.append(step_data)
        
        # Use batched updates instead of immediate database writes to prevent SSE clogging
        if self.enable_batching:
            self._schedule_batch_update()
        else:
            if self.step_count % 5 == 0:
                self.update_usage_record()
    
    def get_step_summary(self) -> Dict[str, Any]:
        """
        Get a summary of step statistics
        
        Returns:
            Dictionary containing step order, counts, and other metrics
        """
        return {
            "total_steps": self.step_count,
            "step_order": self.step_order.copy(),
            "step_type_counts": dict(self.step_type_counts),
            "unique_step_types": len(self.step_type_counts),
            "step_sequence_length": len(self.step_order)
        }
    
    def get_total_tokens(self) -> int:
        """
        Calculate total tokens (input + output) from all logged LLM calls.
        
        Returns:
            Total number of tokens used across all LLM calls
        """
        total_tokens = 0
        for step in self.step_stats:
            # Check for input_tokens and output_tokens in step metadata
            input_tokens = step.get("input_tokens", 0) or 0
            output_tokens = step.get("output_tokens", 0) or 0
            total_tokens += input_tokens + output_tokens
        return total_tokens
    
    def get_total_tool_calls(self) -> int:
        """
        Count total number of tool calls from all logged steps.
        
        Returns:
            Total number of tool calls
        """
        tool_call_count = 0
        for step in self.step_stats:
            # Check if this step is a tool call (has tool_name in metadata)
            if step.get("tool_name"):
                tool_call_count += 1
        return tool_call_count
    
    def cleanup(self):
        """Clean up resources including batch timer"""
        if self.batch_timer:
            self.batch_timer.cancel()
            self.batch_timer = None
        
        # Force final update if there's pending data
        if self.current_record_id and self.enable_batching:
            self._update_record_now()
    
    def log_agent_message(self, message_type: MessageType, content: str, metadata: Optional[Dict[str, Any]] = None) -> None:
        """
        Log an agent message step using MessageType enum
        
        Args:
            message_type: MessageType enum value
            content: Content of the message
            metadata: Additional metadata for the step
        """
        self.log_step(message_type, content, metadata)
    
    def log_tool_call(self, tool_name: str, tool_args: Dict[str, Any], execution_time: Optional[float] = None) -> None:
        """
        Log a tool call step
        
        Args:
            tool_name: Name of the tool called
            tool_args: Arguments passed to the tool
            execution_time: Time taken to execute the tool
        """
        metadata = {
            "tool_name": tool_name,
            "tool_args_count": len(tool_args),
            "execution_time": execution_time
        }
        
        self.log_step(MessageType.TOOL, f"Called {tool_name}", metadata)
    
    def log_code_execution(self, code_length: int, execution_time: Optional[float] = None, 
                          has_error: bool = False) -> None:
        """
        Log a code execution step
        
        Args:
            code_length: Length of executed code
            execution_time: Time taken to execute
            has_error: Whether execution had errors
        """
        metadata = {
            "code_length": code_length,
            "execution_time": execution_time,
            "has_error": has_error
        }
        
        self.log_step(MessageType.CODE, f"Executed {code_length} chars of code", metadata)
    
    def log_llm_call(self, model: str, input_tokens: Optional[int] = None, 
                     output_tokens: Optional[int] = None, execution_time: Optional[float] = None) -> None:
        """
        Log an LLM call step
        
        Args:
            model: Model used for the call
            input_tokens: Number of input tokens
            output_tokens: Number of output tokens
            execution_time: Time taken for the call
        """
        metadata = {
            "model": model,
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "execution_time": execution_time
        }
        
        # Use STATUS for LLM calls as they represent system status
        self.log_step(MessageType.THOUGHT, f"Called {model}", metadata)

def create_usage_record(
    user_id: str,
    chat_id: str,
    query_type: str = "agent_query",
    query_id: str = None,
    mode: str = "dev",
    first_query_bool: Optional[bool] = None,
    query_text: Optional[str] = None,
) -> Optional[int]:
    """
    Create a new usage record
    
    Args:
        user_id: User identifier
        chat_id: Chat identifier
        query_type: Type of query being processed (used as query_string for title generation)
        query_id: Query identifier
        mode: Mode ('dev' or 'prod')
        
    Returns:
        Record ID if successful, None otherwise
    """
    tracker = UsageTracker(user_id, chat_id, query_id, mode=mode)
    return tracker.create_usage_record(
        query_type,
        first_query_bool=first_query_bool,
        query_text=query_text,
    )

def update_usage_record_by_query_id(query_id: str, status: str, additional_data: Optional[Dict[str, Any]] = None, mode: str = "dev") -> bool:
    """
    Update an existing usage record by query_id
    
    Args:
        query_id: Query ID of the record to update (unique identifier from frontend)
        status: Current status
        additional_data: Additional data to update
        mode: Mode ('dev' or 'prod')
        
    Returns:
        True if successful, False otherwise
    """
    try:
        backend = get_storage_backend()
        current_time = datetime.now(timezone.utc).isoformat()
        update_data = {"updated_at": current_time}
        if additional_data:
            update_data.update(additional_data)
        backend.update_usage_record_by_query_id(query_id, status, update_data, mode=mode)
        logger.info(f"Updated usage record by query_id={query_id} with status: {status}")
        return True
        
    except Exception as e:
        logger.error(f"Error updating usage record (query_id={query_id}): {str(e)}")
        return False


def complete_usage_record_by_query_id(query_id: str, final_status: str = "completed", 
                         final_data: Optional[Dict[str, Any]] = None, mode: str = "dev") -> bool:
    """
    Complete a usage record by query_id
    
    Args:
        query_id: Query ID of the record to complete (unique identifier from frontend)
        final_status: Final status
        final_data: Final data to update
        mode: Mode ('dev' or 'prod')
        
    Returns:
        True if successful, False otherwise
    """
    try:
        backend = get_storage_backend()
        current_time = datetime.now(timezone.utc).isoformat()
        update_data = {
            "completed_at": current_time,
            "updated_at": current_time,
        }
        if final_data:
            update_data.update(final_data)
        backend.complete_usage_record_by_query_id(query_id, final_status, update_data, mode=mode)
        logger.info(f"Completed usage record by query_id={query_id} with status: {final_status}")
        return True
        
    except Exception as e:
        logger.error(f"Error completing usage record (query_id={query_id}): {str(e)}")
        return False