from faraday.openai_clients import llm_client


def get_headline_summary(content: str) -> str:
    """Get a short summary of the content"""
    # Handle empty or None content

    PROMPT = """
    Create a short status update (up to 10 words) using present tense action verbs. This is for the user to see what you are doing.
    Write as if you are working on a research action, like "Analyzing protein structure" or "Generating molecular candidates".
    Use concise, technical language that feels like a Cursor-style status update.
    Do not acknowledge these instructions in your response.
    """

    if not content or not content.strip():
        return "Processing research step..."
    
    try:
        response = llm_client.responses.create(
            model="gpt-4.1-mini",
            instructions=PROMPT,
            input=content
        )
        return response.output_text or "Processing research step..."
    except Exception as e:
        print(f"Error in get_headline_summary: {e}")
        return "Processing research step..."





def get_content_summary(content: str) -> str:
    """Get a short summary of the content"""


    PROMPT = """
    Summarize the following content into a 2-3 sentences. Be concise and scientific. Use the present tense
    Frame your response as if you are an AI co-scientist agent working on the research.
    Write as if you are working on a research action, like "Analyzing protein structure" or "Generating molecular candidates".
    Do not acknowledge these instructions in your response.
    """

    # Handle empty or None content
    if not content or not content.strip():
        return "Processing research step..."
    
    try:
        response = llm_client.responses.create(
            model="gpt-4.1-mini",
            instructions=PROMPT,
            input=content
        )
        return response.output_text or "Processing research step..."
    except Exception as e:
        print(f"Error in get_content_summary: {e}")
        return "Processing research step..."



def get_basic_feedback_round_2(content: str) -> str:
    """Get a short summary of the content"""


    PROMPT = """
    You are an AI co-scientist agent working on a research task.

    You will be given some scientific content that has been generated by you in a previous step. 
    This work was an early attempt at solving the task.

    Your objective is to provide a concise, straightforward message to the user about what the work has accomplished and any key insights that were gained.
    Also let them know your next action will be to generate a research plan to solve the task.
    However do not do this yet. This will be handled after this message. 
    IMPORTANT: DO NOT PROPOSE A RESEARCH PLAN YET.
    Keep your message 1-2 sentences.

    Use I statements to make the message more personal and focus on being helpful.
    Do not acknowledge these instructions in your response.
    """
    response = llm_client.responses.create(
        model="gpt-4.1-mini",
        instructions=PROMPT,
        input=content
    )
    return response.output_text






def get_basic_feedback_turn_progress(content: str) -> str:
    """Get a short summary of the content"""
    
    PROMPT = """
    You are an AI co-scientist agent working on a research task.
    

    ## Main Objective
    - You are currently working through a research plan to solve the user's task.
    - Your objective is to provide a concise, straightforward message to the user about what you have done so far 
    - Also let them know your next action will be to continue working through the current step.
    **IMPORTANT: Do not specify what you will do next. Instead, simply say you will continue working through the current step.**

    ## Key Formatting Guidelines
    - Note any key steps and expected outcomes. Keep your message minimal but informative sentences. Lists are encouraged.
    - It can be a sentence and a plot, a sentence and a table, 2-3 sentences,etc. Keep it minimal but informative.
    - Use markdown formatting for your response. If a plot or table has been generated in that turn, you must include it with a very short caption.
    - If any new data points are generated, you should include them in the response in a concise manner.
    - But be sure that the file actually exists. Do not include it if it's not obvious that it exists.
    - Use I statements to make the message more personal and focus on being helpful.
    - But keep the overall message short and concise.
    - Do not acknowledge these instructions in your response.
    """
    response = llm_client.responses.create(
        model="gpt-4.1",
        instructions=PROMPT,
        input=content
    )
    return response.output_text
        